# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 478)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(630, 300, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.buttonStart.setFont(font)
        self.buttonStart.setStyleSheet("background-color: rgb(127,255,0);")
        self.buttonStart.setObjectName("buttonStart")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(630, 120, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 30, 181, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comL = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comL.setFont(font)
        self.comL.setObjectName("comL")
        self.verticalLayout.addWidget(self.comL)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sOpen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sOpen.setFont(font)
        self.sOpen.setObjectName("sOpen")
        self.horizontalLayout.addWidget(self.sOpen)
        self.sClose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sClose.setFont(font)
        self.sClose.setObjectName("sClose")
        self.horizontalLayout.addWidget(self.sClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(0, 0, 620, 480))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("backgraund_to_load.jpg"))
        self.label_image.setScaledContents(False)
        self.label_image.setWordWrap(False)
        self.label_image.setObjectName("label_image")
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setGeometry(QtCore.QRect(630, 260, 181, 22))
        self.slider.setAutoFillBackground(False)
        self.slider.setMaximum(100)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider.setTickInterval(10)
        self.slider.setObjectName("slider")
        self.label_slide = QtWidgets.QLabel(self.centralwidget)
        self.label_slide.setGeometry(QtCore.QRect(620, 240, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_slide.setFont(font)
        self.label_slide.setMouseTracking(False)
        self.label_slide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_slide.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slide.setObjectName("label_slide")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Експеримент №_: Коливання"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">1. Виберіть COM-порт.<br/>2. Натисніть &quot;Open&quot;.<br/>3. Запустіть лабораторний <br/>стенд кнопкою &quot;Start&quot;</span></p></body></html>"))
        self.sOpen.setText(_translate("MainWindow", "Сonnect"))
        self.sClose.setText(_translate("MainWindow", "Disconnect"))
        self.label_slide.setText(_translate("MainWindow", "0%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
